"""Generate src/shared/hanzi.ts — an example character for each syllable+tone.

Sources, in priority order:
  1. guoyunhe/pinyin-json `pinyin-hanzi-table.json` — pinyin -> hanzi ordered by
     frequency, so the first entry is the most recognisable character.
  2. mozillazg/pinyin-data `kTGHZ2013.txt` — the 8105 characters of the
     通用规范汉字表, used only where source 1 has nothing.

Candidates are restricted to the 通用规范汉字表 so the output stays simplified
(source 1 also lists traditional forms) and within the BMP so every glyph is
guaranteed to render.

Anything still unmatched is a tone that does not exist in Mandarin (e.g. `bán`,
`dē`) and is left out so the UI can show a placeholder.

Vulgar characters are excluded outright — see BLOCKED_CHARS / BLOCKED_KEYS.
"""
import json

from blocked import BLOCKED_CHARS, BLOCKED_KEYS
from tonemark import format_pinyin, load_readings

freq = json.load(open('data/ph.json'))
tghz = load_readings('data/tghz.txt')
syllables = json.load(open('syllables.json'))

# The frequency table mixes simplified and traditional forms (e.g. both 是 and
# 視). Restricting to characters in the 通用规范汉字表 keeps the output
# simplified, which is what the rest of the page uses.
standard = {c for chars in tghz.values() for c in chars}

entries = {}
from_primary = from_fallback = 0

for s in syllables:
    for tone in (1, 2, 3, 4):
        if f'{s}{tone}' in BLOCKED_KEYS:
            continue
        key = format_pinyin(s, tone)
        primary = [c for c in freq.get(key, []) if c in standard and c not in BLOCKED_CHARS]
        fallback = [
            c
            for c in tghz.get(key, [])
            if len(c) == 1 and ord(c) <= 0xFFFF and c not in BLOCKED_CHARS
        ]

        if primary:
            entries[f'{s}{tone}'] = primary[0]
            from_primary += 1
        elif fallback:
            entries[f'{s}{tone}'] = fallback[0]
            from_fallback += 1

# Characters legitimately shared by two tones of the same syllable (晃 is both
# huǎng and huàng). Reported for visibility; they are correct, not a bug.
shared = {}
for s in syllables:
    by_char = {}
    for tone in (1, 2, 3, 4):
        c = entries.get(f'{s}{tone}')
        if c:
            by_char.setdefault(c, []).append(tone)
    for c, tones in by_char.items():
        if len(tones) > 1:
            shared.setdefault(c, []).append((s, tones))

total = len(syllables) * 4
missing = total - len(entries)

lines = [
    '// AUTO-GENERATED by build_hanzi.py — do not edit by hand.',
    '//',
    '// An example character for each syllable+tone, e.g. "ba1" -> 八.',
    '// Sources: guoyunhe/pinyin-json (frequency ordered) with a fallback to the',
    '// 通用规范汉字表 (kTGHZ2013). Tones that do not exist in Mandarin are absent,',
    '// so callers must handle a miss.',
    '//',
    '// 脏话/脏字 are filtered out — see BLOCKED_CHARS / BLOCKED_KEYS in build_hanzi.py.',
    '',
    'export const HANZI: Record<string, string> = {',
]
for k, v in entries.items():
    lines.append(f'  {k}: "{v}",')
lines.append('}')
lines.append('')

with open('src/shared/hanzi.ts', 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines))

# Guard against a bad source row leaking anything other than one standard,
# BMP character into the bundle.
bad = {k: v for k, v in entries.items() if len(v) != 1 or ord(v) > 0xFFFF or v not in standard}
assert not bad, f'non-standard values: {list(bad.items())[:10]}'

# Guard against a vulgar character slipping back in if the sources change.
leaked = {k: v for k, v in entries.items() if v in BLOCKED_CHARS}
assert not leaked, f'脏话/脏字 leaked: {list(leaked.items())[:10]}'

print(f'total combos : {total}')
print(f'  primary    : {from_primary}')
print(f'  fallback   : {from_fallback}')
print(f'  no char    : {missing}  (invalid tone -> placeholder)')
print(f'  shared char: {len(shared)} syllables reuse a character across tones')
print(f'    {list(shared.items())[:10]}')
print(f'wrote src/shared/hanzi.ts ({len(entries)} entries)')
